name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

    - name: Build Docker image
      run: |
        cd Task4
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)  # Use current date and time as tag
        docker build -t custom-image:$IMAGE_TAG .

    - name: Tag Docker image
      run: |
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)  # Use current date and time as tag
        docker tag custom-image:$IMAGE_TAG ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG

    - name: Push Docker image to ECR
      run: |
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)  # Use current date and time as tag
        docker push ${{ secrets.ECR_REPOSITORY_URI }}:$IMAGE_TAG
